### ISSUE TITLE
Implement the block with mappings + “Map to selection” button

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#23]
Blocked by #22, implementation is to start when we complete the redesign of this section.

**Comment by joj0s** [comment]
Just to clarify the scope of this issue, according to the mockup, since the 'Terms awaiting creation' table relies on the 'Map to new term' action being implemented, I think this issue include the 'Suggested Terms' table along with the mapping functionality, and issue #27 should include the table holding the newly created terms

**Comment by tskir** [comment]
Yes, exactly—
* This issue: "Suggested terms" table + "Map to selection" button
* #27: "Terms awaiting creation" table + "Create and map to new term" button
