### ISSUE TITLE
Design a page to display status & trigger external imports

### ISSUE THREAD

**Issue by tskir** [EBIvariation/trait-curation#32]
There are three external datasources which the app will communicate with:
* Importing trait names from ClinVar #14 
* Obtaining possible mappings from ZOOMA #30 
* Querying OLS to update ontology term status #31 

This page will be essentially an extension of the "External datasources" page which you added in #39. Here are my thoughts on what we could include on that page:
* Buttons for triggering ClinVar, OLS, ZOOMA imports
* Configuration variables:
  + URL for ClinVar download (currently https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/variant_summary.txt.gz)
  + How frequently to trigger re-imports of 
  + Base URLs for OLS and ZOOMA
* Status of import for all three datasources
  + If a particular import is currently in progress, display "In progress"
  + If failed, display "Failed"
  + Otherwise, display the timestamp on when the import was last performed
* Development options:
  + Button for purging the entire database
  + A number of rows to import from `variant_summary.txt.gz` (to avoid importing the full set, which may take a lot of time and run over Heroku free limits)

**Comment by tskir** [comment]
Since this page seems handy to have, including for development/debugging purposes, I've raised the priority to high. I have also amended the description of this issue to include some things which can be added to this page.

**Comment by joj0s** [comment]
https://www.figma.com/file/pd5DHJSsldVtJcbp4RvkPb/GSoC-Trait-Mapping-App?node-id=0%3A1
Here is a prototype of this page that I created. I haven't included development button such as "Import dummy data" or "Purge database" since this is supposed to be the production prototype, so I can add those at the top or bottom of the page.

**Comment by tcezard** [comment]
The prototype looks good I have a couple of comments:
 - The section titles are not all placed the same way: Source of mapping suggestion and Source of ontology term information are in line with the logo but Trait name sources is above. Also the first two are lowercase and the third upper case. I would suggest they should all look like Trait name sources
 - I would place the Configure button on the right of the import now button
 - The configure expand arrow should pointing to the right  when collapsed and down when expanded

**Comment by joj0s** [comment]
> The section titles are not all placed the same way

Regarding this one, the idea is that 'TRAIT NAME SOURCES` is supposed to be a general section title, meaning that more trait name sources can be added later, besides ClinVar, as a list, beneath the 'TRAIT NAME SOURCES' section. I'm not sure if that makes sense? If not, let me know so I can clarify more on that. 

Otherwise should I leave it as is, change it, or maybe I should add a similar title for the rest of the data sources, something like 'ONTOLOGY TERM SOURCES' ?

Besides that, the rest of the comments have been addressed and the prototype has been updated.

**Comment by joj0s** [comment]
I have gone through the changes mentioned in yesterday's call, feel free to take a look and tell me your thoughts: https://www.figma.com/file/pd5DHJSsldVtJcbp4RvkPb/GSoC-Trait-Mapping-App?node-id=0%3A1

**Comment by joj0s** [comment]
Also I can't seem to find an issue regarding the implementation of this page. I will go ahead an create one.

**Comment by tskir** [comment]
The mockup looks good to me! I'm going to close this issue, and you may go ahead and proceed with the implementation.
