### ISSUE TITLE
Multiple trait names on single 'PhenotypeList" columns during latest ClinVar import

### ISSUE THREAD

**Issue by joj0s** [EBIvariation/trait-curation#84]
During the latest ClinVar import I encountered some weird behaviour. There were multiple trait names for single records, seperated by '|', looking like this: 
![image](https://user-images.githubusercontent.com/36301625/90644809-d739e700-e23d-11ea-8efa-062bfa03bf67.png)

In all past releases, they were separated with semicolons.

I imagined it was a bug with the parsing script, however when I downloaded the latest ClinVar relese manually, it turns out the PhenotypeList column contained a lot of those records:
![image](https://user-images.githubusercontent.com/36301625/90644983-11a38400-e23e-11ea-9781-959590e0b029.png)

Is this behaviour to be expected?

**Comment by joj0s** [comment]
If this is not a bug but something that is to be expected, we should also probably rethink issue #76, so let's clear this up before I get on that.

**Comment by tskir** [comment]
This is an expected change in ClinVar TSV data format. From the [README](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/tab_delimited/README):

----

Beginning in August 2020, the values for referenceAllele and alterateAllele were reverted to represent right-shifted locations. Columns for vcf_pos, vcf_ref, and vcf_alt were added to represent the left-shifted location, as in the VCF standard. These locations are reported so that they are consistent with the data in the XML files. In each row, either vcf_pos/vcf_ref/vcf_alt OR start/stop/referenceAllele/alternateAllele are provided, but not both.

Other changes:
- variants that only have a location on NCBI36 are now included
- the Type "undetermined variant" is now reported as "variation" to be consistent with the XML files
- **RCVAccession is now a unique list of accessions, separated by a pipe.**
- PhenotypeID has the IDs listed when there are 5 or fewer reported conditions; multiple IDs for one trait are separated by a comma, and multiple traits for one RCV are separated by a semicolon. When there are >5 reported conditions, the number of conditions is reported instead. '-' means that there was an error in calculating the ID.
- **PhenotypeList has the names listed when there are 5 or fewer reported conditions. When there are >5 reported conditions, the number of conditions is reported instead.**
- SubmitterCategories now reports 4 for "none" for included variants.
- For an included variant, VariationID now reports the Variation ID(s) for haplotypes or genotypes that include the variant, as clinvar:12345.

**Comment by tskir** [comment]
The most important change for us is that when there are more than 5 conditions associated with a given variant, they won't report their names anymore, and only the count. This means that in the long run **we will not be able to use the `variant_summary.tsv` file as input anymore,** because it will not contain all of the data we need.

I see three solutions to this issue, each one more complex and long term than the last. We will probably implement them in sequence:
* (immediate) For now, just hardcode the latest TSV release where this change does not occur (so probably the latest July release, or the latest August one), so that the app will still work
* (short term) Modify the logic of parsing `variant_summary.tsv` to accommodate the new file format. Rows which contain more than 5 records in PhenotypeList column will have to be skipped for now.
* (mid to long term) Migrate to use the full XML dump. This is actually aligned with the main eva-opentargets pipeline, where I also have plans to eventually migrate away from using TSV and VCF dumps and always use XML, as it's the original and the most complete one.

**Comment by tskir** [comment]
I'm setting this to 1.0 milestone, meaning only the immediate + short term solutions. The long term solution will be implemented separately. Created an issue in the backlog for that: #89
